---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "Eclipse Milo OPCUA Client implementation Component."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:    
    Opcua_Endpoint: "opc.tcp://localhost:55380/UA/NodeRed"
    accessControl:      
      aws.greengrass.ShadowManager: # to interact with core device shadow
        com.example.Opcua:shadow:1:
            policyDescription: 'Allows access to GG core device named shadow'
            operations: # only allow required access in production
              - aws.greengrass#GetThingShadow
              - aws.greengrass#UpdateThingShadow                                     
            resources:
              - "$aws/things/{iot:thingName}/shadow/name/opc"           
      aws.greengrass.ipc.pubsub:  # to receive subscriptions callbacks from core device
        com.example.Opcua:pubsub:2:
          policyDescription: 'Allows subscription to GG core device named shadow'
          operations:
            - 'aws.greengrass#SubscribeToTopic' # gets callbacks upon shadow changes      
          resources:
            - $aws/things/{iot:thingName}/shadow/name/opc/update/delta   # delta updates for core device shadow  
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/OpcUA-1.0.0.jar"
    Lifecycle:
      Run: "java -cp {artifacts:path}/Opcua-1.0.0.jar com.example.Opcua {configuration:/Opcua_Endpoint}"